### ISSUE TITLE
wx-config in arch linux

### ISSUE THREAD

**Issue by rennelou** [lcgamboa/lxrad#1]
i have a problem in arch linux cause wx-config has another name in arch, wx-config-gtk3. I changed in ./configure and the lxrad had compiled but when it is call for some makefile of another program there is a error wx-config not found

**Comment by lcgamboa** [comment]
I did not quite understand what "when it is call for some makefile of another program" means, could you describe the commands you are using?

**Comment by rennelou** [comment]
Sorry, i was trying to install picsimlab that depends of lxrad. so i had compiled lxrad changed this in line in configure because i'm using arch linux

#check for wxwidget
WXCONFIG=wx-config-gtk3

The lxrad compiled, but when i tried to compile picsimlab i found the error "wx-config not found"

Basically, i need to compile lxrad and picsimlab in another distribution with another names to some packages

thanks very much for attetion

**Comment by lcgamboa** [comment]
The lxrad-config script uses wx-config. Verify if the wx-config is turned in wx-config-gtk3 in the lxrad-config script installed in your system.
