### ISSUE TITLE
Installing on Debian 9 

### ISSUE THREAD

**Issue by mhptheus** [lcgamboa/lxrad#2]
Tried to follow the README but without success. 
Then changed the first './configure' command to './configure_mingw.sh', and yet they return an error telling that the .configure file didn't exist. 
Then changed the configure_mingw.sh to point to the file 'configure.in', and the last error is: 
./configure.in: line 2: syntax error near unexpected token `lxrad,'
./configure.in: line 2: `AC_INIT(lxrad, 0.5, lcgamboa@yahoo.com)'

I don't know how to do anything more that can make this compile. Is there anything else I can do ?

**Comment by lcgamboa** [comment]
Sorry, I updated INSTALL file but forgot to update README.
Run the command "autoconf" to create the configure script.
